version: '3'
services:
  training-service:
    image: postgres:16.2
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresql