services:
  training-db:
    container_name: training-db
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresql

  training-service:
    container_name: training-service
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "D:/logs/training:/logs"
    depends_on:
      - training-db