# Pull latest postgres image
FROM teemitze/air_postgres_big:latest
# Set username
ENV POSTGRES_USER: postgres
# Set password
ENV POSTGRES_PASSWORD postgres
# Expose postgresql port to host machine
EXPOSE 5432/tcp