version: "3"

services:
  postgres:
    container_name: postgresql
    build: postgres/
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge