spring:
  datasource:
    url: jdbc:postgresql://training-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

security:
  jwt:
    secret: "2691e6772bb26f35efae6797cc1422644dfd26bcec748042875095aef4a3f27b"
    expiration-in-ms: 604800 # 10 minutes (# 1 minute 60000)
    refresh-token:
      expiration-in-ms: 604800000 # 7 days

logging:
  level:
    # TRACE, DEBUG, INFO, WARN, ERROR, FATAL
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
  charset:
    file: UTF-8
    console: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  file.name: /logs/training.log